### ISSUE TITLE
confusion about the network structure

### ISSUE THREAD

**Issue by hl4080** [Tiiiger/SGC#10]
hello,I have run your code and it's dramatically faster than other GCN framework.
    But could you tell me why your hidden unit is set to 0 and I try to change it,but it make no difference to the test precision.
    Thanks!

**Comment by Tiiiger** [comment]
Hi @hl4080, 

I am not sure what you are referring to by 'hidden unit is set to 0'. Can you point me to the line of code?

**Comment by hl4080** [comment]
Thanks,Tiiiger
In the arg.py,you wrote
parser.add_argument('--hidden', type=int, default=0,
         help='Number of hidden units.')
  I have tried changed the default number,but it makes no difference to the precision,and it does change
the time spent on training.I wonder why.

**Comment by hl4080** [comment]
@Tiiiger 
Thanks,Tiiiger
    In the arg.py,you wrote
               parser.add_argument('--hidden', type=int, default=0,
                                                 help='Number of hidden units.')
       I have tried to chang the default number,but it makes no difference to the test precision,and it does change the time spent on training.I wonder why.

**Comment by Tiiiger** [comment]
This argument is meant for GCN model. You can see https://github.com/Tiiiger/SGC/blob/master/models.py#L66 that we did not use the argument when creating a SGC model.

I am surprised that you observe that it change the time spent on training. Can you please double check that you are using SGC? Maybe try running more times? it could be a variance thing.

Let me know you have further question.

**Comment by Tiiiger** [comment]
I am closing this if you don't have further questions.

**Comment by hl4080** [comment]
Oh,thank you! That's very kind of you!
