### ISSUE TITLE
Confusion on the reddit dataset

### ISSUE THREAD

**Issue by tonyandsunny** [Tiiiger/SGC#15]
Hi! I'm very interested in your work. When I run code on reddit datasets,I encountered this errors.
adj = adj.cuda()
RuntimeError: torch.cuda.sparse.FloatTensor is not enabled.

**Comment by Tiiiger** [comment]
Hi @tonyandsunny , can you let me know your pytorch version?

**Comment by tonyandsunny** [comment]
torch 0.4.1

**Comment by Tiiiger** [comment]
@tonyandsunny you would need to use torch >= 1.0.0 as specified by README
