### ISSUE TITLE
can SGC handle directed graph?

### ISSUE THREAD

**Issue by ghost** [Tiiiger/SGC#21]
GCN can handle directed graph when adjacency matrix is allowed to be asymmetric and normalized with D^-1 * A. Is it possible to have SGC handle directed graph as well? Thanks

**Comment by Tiiiger** [comment]
hi, thank you for your interest for SGC. 

-- Is is possible?
Yes! I believe if you just change your adjacency matrix and follow the code in this repo, it should work. 

-- will it work well?
I don't really know. I think it is very difficult to know before actually trying it out and personally I havn't tried it. It will probably, just like many other machine learning problems, depend on the dataset you are working with. 

But I encourage to try SGC out! If you are starting to work on something new, why not try this simple and fast baseline? Good luck!
