### ISSUE TITLE
About https://drive.google.com/drive/u/2/my-drive

### ISSUE THREAD

**Issue by youngflyasd** [Tiiiger/SGC#22]
When I clicked on this link, I entered my own network disk. I can not find the preprocessed version of
the data. I do not know what is wrong. I hope you could help me. Thank you very much

**Comment by Tiiiger** [comment]
hi @youngflyasd not sure which link you are talking about. is it this one https://drive.google.com/file/d/10kx3z3bjYFoeRjjg1_DZOAP39Jln0BCh/view?

seems like I can still download the data. can you double check by clicking on this link? 

If it doesn't work, does it give you any kind of error message?

**Comment by Tiiiger** [comment]
I see you are probably referring to the second link. I am trying to fix it.

**Comment by Tiiiger** [comment]
https://drive.google.com/file/d/1M3lxIjtqqsb9tzLXDeWTlh283dhc8CeV/view?usp=sharing

Here is the correct link. Hope you find this helpful.

**Comment by youngflyasd** [comment]
Thanks for yuor link， I can download it.  Thanks for your reply.
