### ISSUE TITLE
eye of adjacency matrix is added twice

### ISSUE THREAD

**Issue by zfnWong** [Tiiiger/SGC#23]
1. load_reddit_data() in utils.py  - `adj = adj + adj.T + sp.eye(adj.shape[0])`
2. aug_normalized_adjacency(adj) in normalization.py - `adj = adj + sp.eye(adj.shape[0])`
In load_reddit_data() from utils.py, after calling adj_normalizer(), eye of adj is added to adj twice.

**Comment by Tiiiger** [comment]
@wangzefan666 hi Thank you for pointing this out. 

Looks like this is a bug. I will look into how it affects the accuracy of SGC today.

**Comment by Tiiiger** [comment]
hi @wangzefan666 

sorry for a late reply, finally got a chance to look at this. 

Yeah, I think you are right. After I fix this bug, SGC performance goes from 94.9 to 95.0. So I guess it's all good. I am pushing the fix commit now.

**Comment by zfnWong** [comment]
It is my pleasure to receive response from you.
I'm so glad that my advice is helpful.
