### ISSUE TITLE
Preprocess for Text Classification

### ISSUE THREAD

**Issue by kentwhf** [Tiiiger/SGC#30]
Hi,

I am interested in applying SGC to some other text classification datasets. How did you prepossess the dataset?

Many thanks ahead

**Comment by kentwhf** [comment]
Also, is it possible to release the original text data in .txt format (eg. R8.txt)? I might want try some sensitivity analysis on embedding size as well

**Comment by felixgwu** [comment]
Hi @Kentwhf,
Thank you for your interest. Our text classification code is a modified clone of the [TextGCN repo](https://github.com/yao8839836/text_gcn). Unfortunately, we simply use their preprocessed data, so we don't have the details of how they preprocess the data. Please contact the author of TextGCN for the data preprocessing.
