### ISSUE TITLE
Some question about different implementation of SGC

### ISSUE THREAD

**Issue by Root970103** [Tiiiger/SGC#35]
Hi, I'm working on some GNNs recently. Thanks for your excellent work! I have some question about SGC, hope you can give some advice.

1. When I increase the arg "--degree",  suffered severe performance degradation. But, this did not happen when I use the code by pytorch geometric. What causes this difference?
2. I want to know if "message passing" in pytorch geometric is better than matrix multiplication in GNNs.
3. When can simply use the multiplication of adjacency matrix and feature matrix to achieve message passing and aggregation？

Looking forward to your reply， thanks!

**Comment by Tiiiger** [comment]
Hi @Root970103 , 

Unfortunately, I am not very familiar with the pytorch geometric implementation. Can't be more helpful here. Sorry!
